import { Response } from "express";
import Auth from "../server/api/auth";
import Outlet from "../server/api/outlet";
import Role from "../server/api/role";
import User from "../server/api/user";
import SystemLog from "../server/api/systemLog";
import OutletNotes from "../server/api/outletNotes";
import Tag from "../server/api/tag";
import Section from "../server/api/section";
import TimeSlot from "../server/api/outletTimeSlot";
import TimeSlotOverride from "../server/api/outletTimeSlotOverride";
import PreOrderItem from "../server/api/preOrderItem";
import Floor from "../server/api/floor";
import OutletSeatingType from "../server/api/outletSeatingType";
import OutletBasicInformation from "../server/api/outletBasicInformation";
import Table from "../server/api/table";
import SeatType from "../server/api/seatType";
import SeatingType from "../server/api/seatingType";
import OutletTable from "../server/api/outletTable";
import TableSection from "../server/api/tableSection";
import Reservation from "../server/api/reservation";
import GroupTable from "../server/api/groupTable";
import Company from "../server/api/company";
import Invoice from "../server/api/invoice";
import Customer from "../server/api/customer";
import TagCategory from "./api/tagCategory";
import Booking from "./api/listingView";
import Common from "./api/common";
import SeatingView from "./api/seatingView";
import Coupon from "./api/coupon";
import Material from "./api/materials";
import Category from "./api/category";
import SubCategory from "./api/subCategory";
import DiningOption from "./api/diningOption";
import EmailTemplate from "./api/emailTemplate";
import Ticketing from "./api/ticketing";
import TicketBooking from "./api/ticketBooking";
import SMSTemplate from "./api/smsTemplate";
import IVRS from "./api/ivrs";
import Marketing from "./api/marketing";
import Timeline from "./api/timeline";
import UserPermission from "./api/userPermission";
import AutoTagging from "./api/autoTagging";
import Report from "./api/report";

const AllRoutes = (app: any) => {
  app.use("/api/auth", Auth);
  app.use("/api/outlet", Outlet);
  app.use("/api/role", Role);
  app.use("/api/user", User);
  app.use("/api/systemLog", SystemLog);
  app.use("/api/outletNote", OutletNotes);
  app.use("/api/tag", Tag);
  app.use("/api/section", Section);
  app.use("/api/timeslot", TimeSlot);
  app.use("/api/timeslotoverride", TimeSlotOverride);
  app.use("/api/preorderitem", PreOrderItem);
  app.use("/api/floor", Floor);
  app.use("/api/seatingtype", SeatingType);
  app.use("/api/seattype", SeatType);
  app.use("/api/outletbasicinformation", OutletBasicInformation);
  app.use("/api/outletseatingtype", OutletSeatingType);
  app.use("/api/table", Table);
  app.use("/api/outlettable", OutletTable);
  app.use("/api/tablesection", TableSection);
  app.use("/api/reservation", Reservation);
  app.use("/api/grouptable", GroupTable);
  app.use("/api/company", Company);
  app.use("/api/invoice", Invoice);
  app.use("/api/customer", Customer);
  app.use("/api/tagcategory", TagCategory);
  app.use("/api/booking", Booking);
  app.use("/api/common", Common);
  app.use("/api/seatingview", SeatingView);
  app.use("/api/coupon", Coupon);
  app.use("/api/material", Material);
  app.use("/api/category", Category);
  app.use("/api/subcategory", SubCategory);
  app.use("/api/diningoption", DiningOption);
  app.use("/api/emailtemplate", EmailTemplate);
  app.use("/api/ticket", Ticketing);
  app.use("/api/ticketbooking", TicketBooking);
  app.use("/api/smstemplate", SMSTemplate);
  app.use("/api/ivrs", IVRS);
  app.use("/api/marketing", Marketing);
  app.use("/api/timeline", Timeline);
  app.use("/api/userpermission", UserPermission);
  app.use("/api/autotagging", AutoTagging);
  app.use("/api/report", Report);

  // Default route
  app.get("*", (req: any, res: Response) => {
    // Here user can also design an
    // error page and render it
    return res.status(404).send("Page Not Found");
  });
};

export default AllRoutes;
