export enum Exceptions {
  INVALID_CONFIG = "Invalid config",
  INTERNAL_ERROR = "Something went wrong",
  UNAUTHORIZED_ACCESS = "Unauthorized access",

  INVALID_USERNAME_PASSWORD = "Invalid userName and password",
  INVALID_USER = "Invalid user",

  INVALID_OUTLET = "Invalid outlet",
  INVALID_ROLE = "Invalid role",
  ALREADY_USER_PERMISSION = "User already has this permission",
  INVALID_CODE = "Invalid code",
  INVALID_NOTES = "Invalid Notes",
  USERNAME_ALREADY_EXISTS = "Username already exists",
  INVALID_TAG = "Invalid tag",
  INVALID_SECTION = "Invalid section",
  INVALID_TIMESLOT = "Invalid timeslot",
  INVALID_ITEM = "Invalid item",
  INVALID_FLOOR = "Invalid floor",
  INVALID_TABLE = "Invalid table",
  INVALID_SEATINGTYPE = "Invalid seatingtype",
  INVALID_SEATTYPE = "Invalid seattype",
  INVALID_GROUP = "Invalid group",
  INVALID_GROUP_POSSIBILITY = "Invalid group possibility",
  INVALID_OUTLET_GROUP_TABLE = "Invalid outlet group table",
  CUSTOM_ERROR = "Custom error",
  NAME_ALREADY_EXISTS = "Name already exists",
  INVALID_COMPANY = "Invalid comapany",
  INVALID_DATE_TIME = "Invalid date or time",
  INVALID_INVOICE = "Invalid invoice",
  INVALID_CUSTOMER = "Invalid customer",
  POSSIBILITY_ALREADY_EXISTS = "Possibility already exists",
  INVALID_TAGCATEGORY = "Invalid tag category",
  INVALID_COUPON = "Invalid coupon",
  INVALID_PAX = "Number of pax should be greater than zero",
  INVALID_MATERIAL = "Invalid material",
  INVALID_CATEGORY = "Invalid category",
  INVALID_SUBCATEGORY = "Invalid sub category",
  INVALID_DINING_OPTION = "Invalid dining option",
  INVALID_EMAIL_TEMPLATE = "Invalid email template",
  INVALID_TICKET = "Invalid ticket",
  INVALID_SMS_TEMPLATE = "Invalid sms template",
  INVALID_IVRS_RECORD = "Invalid detail",
  INVALID_MARKETING = "Invalid marketing",
  INVALID_PERMISSION = "Permission not found",
  INVALID_AUTOTAG = "Invalid autoTag",
  INVALID_COMPANY_PERMISSION = "Invalid company permission",
  INVALID_SESSION = "Invalid session",

  INVALID_TABLE_CAPACITY = "We don't have entered pax capacity table, please decrease the capacity and book again",
  BOOKING_TIMESLOTS_FULL = "We don't have table available for this selected time, please change the time and book again",
  INVALID_OUTLET_TABLE = "We don't have table available for this outlet",
  INVALID_MEALTYPE = "We don't have mealType available for this selected time",
  INVALID_MOVE = "Table already have booking for this time slot",
  INVALID_BASKET = "Something wrong with basket",
  INVALID_MAILCHIMP_KEY = "Mailchimp is not integrated yet",
  INVALID_IVRS_KEY = "IVRS is not integrated yet",
  DUPLICATE_IVRS_PHONENO = "IVRS phone number is already present in other outlet",

  INVALID_PAYMENT_TOKEN = "Unable to create payment token",
  INVALID_CARD_ADD = "Unable to add card detail to customer",
  CARD_DETAILS_REQUIRED = "Card details is required",
}
